export const FETCH_DATA_GRAFIK_PEMBELIAN = "FETCH_DATA_GRAFIK_PEMBELIAN";
export const FETCH_DATA_GRAFIK_PENJUALAN_REGULER =
  "FETCH_DATA_GRAFIK_PENJUALAN_REGULER";
export const FETCH_DATA_GRAFIK_PENJUALAN_INDUSTRI =
  "FETCH_DATA_GRAFIK_PENJUALAN_INDUSTRI";
export const FETCH_SELECTED_DATA_GRAFIK_PEMBELIAN =
  "FETCH_SELECTED_DATA_GRAFIK_PEMBELIAN";
export const FETCH_SELECTED_DATA_GRAFIK_PENJUALAN_REGULER =
  "FETCH_SELECTED_DATA_GRAFIK_PENJUALAN_REGULER";
export const FETCH_SELECTED_DATA_GRAFIK_PENJUALAN_INDUSTRI =
  "FETCH_SELECTED_DATA_GRAFIK_PENJUALAN_INDUSTRI";
